.TH comicseer 1

.SH NAME
\fBcomicseer\fP - Digital comic viewer, reader, and manager

.SH SYNOPSIS
.nf
\fBcomicseer\fP [\fIPATH\fP]
.fi

.SH DESCRIPTION
\fBComic Seer\fP is viewer, reader, and manager for digital comic (eComic) files. It currently supports CBZ (zip) and CBR (rar) files. It is simply the faster and most efficient reader for Windows and Linux. For more information, visit the website at http://comicseer.xylasoft.com

.SH ARGUMENTS
.TP
.I PATH
The path to a file to be opened.

.SH BUGS
Please report any bugs via e-mail to comicseer@xylasoft.com or visit the forums at http://comicseer.xylasoft.com/forums

.SH CONTACT
Adam Jordan, Xylasoft <\fIcomicseer@xylasoft.com\fP>
.TP
\fIhttp://comicseer.xylasoft.com\fP
